ALTER TABLE "app_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "auth_flows" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lastfm_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sync_jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_sync_state" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scrobbles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_album_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_artist_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_track_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_year_artist_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "artist_resolutions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_artist_relations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_artists" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_cache_entries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_labels" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_mbid_redirects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_recording_credits" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_recordings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_release_groups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_release_labels" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_releases" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_search_cache" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "mb_tracks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "wd_artist_facts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "wd_entities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "wd_entity_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "llm_calls" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "round_questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "rounds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "bracket_entrants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "bracket_matches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "brackets" ENABLE ROW LEVEL SECURITY;