/**
 * Assemble docs/SCHEMA.md from the hand-written overview and the latest
 * generated migration, so the documented DDL is always the real DDL.
 * Run: npm run render-docs -w @quiztape/db
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, '..');
const repo = resolve(pkg, '..', '..');

const overview = readFileSync(join(pkg, 'SCHEMA_OVERVIEW.md'), 'utf8');
const migrationsDir = join(pkg, 'drizzle');
const sqlFiles = readdirSync(migrationsDir)
  .filter((file) => file.endsWith('.sql'))
  .sort();
if (sqlFiles.length === 0) throw new Error('No migrations found; run npm run generate -w @quiztape/db first');
const ddl = sqlFiles.map((file) => `-- ${file}\n${readFileSync(join(migrationsDir, file), 'utf8')}`).join('\n\n');

const out = `${overview.trimEnd()}

## DDL

Generated by drizzle-kit from \`packages/db/src/schema\`. Do not edit by hand; change the schema and run \`npm run db:generate\`, then \`npm run render-docs -w @quiztape/db\`.

\`\`\`sql
${ddl.trim()}
\`\`\`
`;
writeFileSync(join(repo, 'docs', 'SCHEMA.md'), out);
console.log(`wrote docs/SCHEMA.md (${sqlFiles.length} migration file(s))`);
